apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: tmp
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: imageupdater/yaml
    repoURL: 'https://github.com/Thaliph/demo-argo.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
